# Generated by Django 6.0.7 on 2026-07-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('streak_count', models.IntegerField(default=1)),
                ('checkin_time', models.TimeField(default='21:00')),
                ('what', models.CharField(max_length=120)),
                ('category', models.CharField(default='other', max_length=20)),
                ('why', models.TextField(blank=True)),
                ('minimum_effort', models.CharField(blank=True, max_length=120)),
                ('goal_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_check_in', models.DateTimeField(default=None, null=True)),
                ('reminder_active', models.BooleanField(default=True)),
                ('user_selected_reminder_time', models.TimeField(default=None, null=True)),
                ('mode_of_delivery', models.CharField(default='email', max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='free', max_length=20)),
                ('public_searchable_username', models.CharField(blank=True, max_length=50, unique=True)),
                ('leaderboard_optin', models.BooleanField(default=False)),
                ('streak_count_is_public_visible', models.BooleanField(default=False)),
                ('ai_insight_active', models.BooleanField(default=True)),
                ('receive_newsletter', models.BooleanField(default=False)),
                ('theme', models.CharField(default='dark', max_length=10)),
                ('weekly_report_email_active', models.BooleanField(default=True)),
                ('custom_report_email_active', models.BooleanField(default=False)),
                ('social_mode', models.CharField(default='solo', max_length=10)),
                ('zeal_score', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_at', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.commitment')),
            ],
            options={
                'unique_together': {('commitment_id', 'commit_at')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_rn', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_rn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
