# Generated by Django 6.0.7 on 2026-07-25 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_report_email_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='public_searchable_username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zeal_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('streak_count', models.IntegerField(default=0)),
                ('checkin_time', models.TimeField(default='21:00')),
                ('what', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fitness', 'Fitness'), ('study', 'Study'), ('work', 'Work'), ('health', 'Health'), ('mindset', 'Mindset'), ('other', 'Other')], max_length=20)),
                ('why', models.TextField(blank=True)),
                ('minimum_effort', models.CharField(max_length=120)),
                ('goal_days', models.PositiveIntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_check_in', models.DateTimeField(default=None, null=True)),
                ('reminder_active', models.BooleanField(default=True)),
                ('mode_of_delivery', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='email', max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_at', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('proud', 'Proud'), ('accomplished', 'Accomplished'), ('confident', 'Confident'), ('determined', 'Determined'), ('focused', 'Focused'), ('motivated', 'Motivated'), ('disciplined', 'Disciplined'), ('strong', 'Strong'), ('unstoppable', 'Unstoppable'), ('excited', 'Excited'), ('energetic', 'Energetic'), ('optimistic', 'Optimistic'), ('inspired', 'Inspired'), ('passionate', 'Passionate'), ('courageous', 'Courageous'), ('calm', 'Calm'), ('peaceful', 'Peaceful'), ('content', 'Content'), ('grateful', 'Grateful'), ('hopeful', 'Hopeful'), ('relieved', 'Relieved'), ('satisfied', 'Satisfied'), ('balanced', 'Balanced'), ('patient', 'Patient'), ('present', 'Present'), ('grounded', 'Grounded'), ('loved', 'Loved'), ('supported', 'Supported'), ('connected', 'Connected'), ('appreciated', 'Appreciated'), ('valued', 'Valued'), ('okay', 'Okay'), ('meh', 'Meh'), ('numb', 'Numb'), ('indifferent', 'Indifferent'), ('neutral', 'Neutral'), ('distracted', 'Distracted'), ('restless', 'Restless'), ('bored', 'Bored'), ('curious', 'Curious'), ('tired', 'Tired'), ('exhausted', 'Exhausted'), ('drained', 'Drained'), ('lazy', 'Lazy'), ('unmotivated', 'Unmotivated'), ('sluggish', 'Sluggish'), ('burnt_out', 'Burnt Out'), ('sleepy', 'Sleepy'), ('lethargic', 'Lethargic'), ('worried', 'Worried'), ('anxious', 'Anxious'), ('nervous', 'Nervous'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed'), ('uncertain', 'Uncertain'), ('confused', 'Confused'), ('hesitant', 'Hesitant'), ('doubtful', 'Doubtful'), ('frustrated', 'Frustrated'), ('irritated', 'Irritated'), ('annoyed', 'Annoyed'), ('angry', 'Angry'), ('resentful', 'Resentful'), ('bitter', 'Bitter'), ('disappointed', 'Disappointed'), ('discouraged', 'Discouraged'), ('defeated', 'Defeated'), ('sad', 'Sad'), ('lonely', 'Lonely'), ('isolated', 'Isolated'), ('hopeless', 'Hopeless'), ('empty', 'Empty'), ('ashamed', 'Ashamed'), ('guilty', 'Guilty'), ('regretful', 'Regretful'), ('worthless', 'Worthless'), ('broken', 'Broken'), ('grieving', 'Grieving'), ('depressed', 'Depressed'), ('reflective', 'Reflective'), ('introspective', 'Introspective'), ('thoughtful', 'Thoughtful'), ('nostalgic', 'Nostalgic'), ('humbled', 'Humbled')], max_length=50)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.commitment')),
            ],
            options={
                'unique_together': {('commitment_id', 'commit_at')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_rn', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_rn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
