# Generated by Django 6.0.7 on 2026-07-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('tag', models.CharField()),
                ('excerpt', models.CharField()),
                ('date', models.DateField(auto_now_add=True)),
                ('read_time', models.IntegerField()),
                ('banner', models.URLField()),
                ('featuered', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
