# Generated by Django 6.0.7 on 2026-07-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_news_profile_profile_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entries',
            name='mood',
            field=models.CharField(blank=True, default='minimum', max_length=50),
        ),
    ]
