# Generated by Django 6.0.7 on 2026-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_alter_commitment_streak_count_alter_entries_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='last_is_active_false_date',
            field=models.DateField(auto_now=True),
        ),
    ]
