# Generated by Django 6.0.7 on 2026-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0004_customeuser_last_is_active_false_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='actual_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
