# Generated by Django 6.0.7 on 2026-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_news_actual_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTempToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='featuered',
            new_name='featured',
        ),
    ]
