# Generated by Django 6.0.7 on 2026-08-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0006_stafftemptoken_rename_featuered_news_featured'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'tag', 'excerpt', 'read_time', 'banner', 'featured', 'actual_content')},
        ),
    ]
