# Generated by Django 6.0.7 on 2026-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0007_alter_news_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
