# Generated by Django 6.1 on 2026-08-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_commitment_last_reminder_sent_at_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='pending_notice',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='mode_of_delivery',
            field=models.CharField(default='push', max_length=10),
        ),
        migrations.CreateModel(
            name='PremiumTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('downgraded', models.BooleanField(default=False)),
                ('downgraded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_trial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
