# Generated by Django 6.0.7 on 2026-08-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_commitment_last_reminder_sent_at_pushsubscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'tag', 'excerpt')},
        ),
    ]
