# Generated by Django 6.1 on 2026-08-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_commitment_completed_at_commitment_pending_notice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
