# Generated by Django 6.0.7 on 2026-08-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_alter_news_unique_together'),
        ('origin', '0012_alter_news_excerpt_alter_news_tag_alter_news_title'),
    ]

    operations = [
    ]
