# Generated by Django 6.0.7 on 2026-08-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0013_merge_20260810_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'tag', 'excerpt', 'read_time', 'banner', 'featured', 'actual_content')},
        ),
    ]
