# Generated by Django 6.0.7 on 2026-08-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0014_alter_news_unique_together_alter_news_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'tag', 'banner')},
        ),
    ]
