# Generated by Django 6.0.7 on 2026-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0015_alter_news_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('title', 'tag')},
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(max_length=1001),
        ),
    ]
