# Generated by Django 6.0.7 on 2026-08-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0016_alter_news_unique_together_alter_news_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='last_checkup_notice_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
