# Generated by Django 6.0.7 on 2026-08-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0017_customeuser_last_checkup_notice_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='milestone_100_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commitment',
            name='milestone_50_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
